version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysql-dont-forget-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_USER: dontForget
      MYSQL_PASSWORD: dontForget
      MYSQL_DATABASE : dontForget
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init-files/:/docker-entrypoint-initdb.d
    platform: linux/x86_64